# -*- coding: utf-8 -*-
"""
Created on Wed Jun  5 08:27:21 2019

@author: Casiano.Koprowski
"""

import logging
import os as _os
import pickle as _pickle


def read_pickle(filename: str, pickle_ext: bool = False, logger: logging.Logger = None) -> dict:
    """
    Attempts to open and read in the survey pickle generated by eHydro_scrape.

    This function attempts to find the `.pickle` file by using the file name
    and removing the extension and adding the `.pickle` extension.

    If a `.pickle` exists, the function will open it and return it's dictionary
    contents

    Parameters
    ----------
    filename
        Complete file path of a survey file
    pickle_ext
        whether the pickle has the `.pickle` extension
    logger
        logging object

    Returns
    -------
    dict
        metadata of pickle
    """

    if logger is None:
        logger = logging.getLogger('fuse.read')

    pickle_metadata = {}

    if not pickle_ext:
        filename = _os.path.normpath(f'{_os.path.splitext(filename)[0]}.pickle')

    if _os.path.exists(filename):
        with open(filename, 'rb') as pickle_file:
            pickle_metadata = _pickle.load(pickle_file)
    else:
        logger.warning(f'{filename} not found')

    return pickle_metadata
