# -*- coding: utf-8 -*-
"""
Created on Wed Jun  5 08:27:21 2019

@author: Casiano.Koprowski
"""

import os as _os
import pickle as _pickle


class PickleFile:
    """TODO write description"""

    def __init__(self, infilename):
        """
        TODO write description

        :param infilename: Complete file path of a survey .xyz file
        """

        self.pickle_meta = self.read_pickle(infilename)
        self.dict_keys = self.collect_keys(self.pickle_meta)

    def read_pickle(self, infilename: str, pickle_ext: bool = False):
        """
        Attempts to open and read in the survey pickle generated by
        eHydro_scrape.

        This function atempts to find the .pickle file by using the survey name
        and removing the .xyz extension and adding the .pickle extension.

        If a .pickle exists, the function will open it and return it's
        dictionary contents

        Parameters
        ----------
        infilename
            Complete file path of a survey .xyz file
        pickle_ext

        Returns
        -------

        """
        if not pickle_ext:
            froot, fname = _os.path.split(infilename)
            fname, fext = _os.path.splitext(fname)
            fpickle = _os.path.join(froot, f'{fname}.pickle')
            fpickle = _os.path.normpath(fpickle)
        else:
            fpickle = infilename
        if _os.path.exists(fpickle):
            opened = open(fpickle, 'rb')
            pickle_meta = _pickle.load(opened)
            opened.close()
            return pickle_meta
        else:
            print(f'{fpickle} not found')
            return {}

    def collect_keys(self, dictionary: dict) -> tuple:
        return (key for key in dictionary.keys())


def read_pickle(infilename: str, pickle_ext: bool = False) -> dict:
    """
    Attempts to open and read in the survey pickle generated by
    eHydro_scrape.

    This function atempts to find the .pickle file by using the survey name
    and removing the .xyz extension and adding the .pickle extension.

    If a .pickle exists, the function will open it and return it's
    dictionary contents

    Parameters
    ----------
    infilename
        Complete file path of a survey .xyz file
    pickle_ext

    Returns
    -------

    """
    if not pickle_ext:
        froot, fname = _os.path.split(infilename)
        fname, fext = _os.path.splitext(fname)
        fpickle = _os.path.join(froot, f'{fname}.pickle')
        fpickle = _os.path.normpath(fpickle)
    else:
        fpickle = infilename
    if _os.path.exists(fpickle):
        opened = open(fpickle, 'rb')
        pickle_meta = _pickle.load(opened)
        opened.close()
        return pickle_meta
    else:
        print(f'{fpickle} not found')
        return {}


def dict_keys(dictionary: dict) -> tuple:
    return tuple(key for key in dictionary.keys())
