# -*- coding: utf-8 -*-
"""
Created on Wed Jun  5 08:27:21 2019

@author: Casiano.Koprowski
"""

import os as _os
import pickle as _pickle


class pickle_file:
    """TODO write description"""

    _eHyo = ["OBJECTID", "SURVEYJOBIDPK", "SURVEYAGENCY", "CHANNELAREAIDFK",
             "SDSFEATURENAME", "SOURCEPROJECTION", "SOURCEDATALOCATION",
             "SURVEYDATEUPLOADED", "SURVEYDATEEND", "SURVEYDATESTART",
             "SURVEYTYPE", "PROJECTEDAREA", "SOURCEDATAFORMAT",
             "Shape__Area", "Shape__Length", 'poly', 'poly_name']

    def __init__(self, infilename):
        """
        TODO write description

        :param infilename: Complete file path of a survey .xyz file
        """

        self.pickle_meta = self.read_pickle(infilename)

    def read_pickle(self, infilename: str):
        """
        Attempts to open and read in the survey pickle generated by
        eHydro_scrape.
        
        This function atempts to find the .pickle file by using the survey name
        and removing the .xyz extension and adding the .pickle extension.
        
        If a .pickle exists, the function will open it and return it's
        dictionary contents

        Parameters
        ----------
        infilename :
            Complete file path of a survey .xyz file
        infilename: str :
            

        Returns
        -------

        """

        froot, fname = _os.path.split(infilename)
        fname, fext = _os.path.splitext(fname)
        fpickle = _os.path.join(froot, fname + '.pickle')
        fpickle = _os.path.normpath(fpickle)
        if _os.path.exists(fpickle):
            opened = open(fpickle, 'rb')
            pickle_meta = _pickle.load(opened)
            opened.close()
            return pickle_meta
        else:
            print(fpickle + ' not found')
            return {}
